---
Name: omnipay-routes
After: framework/routes#coreroutes
---
SilverStripe\Control\Director:
  rules:
    'paymentendpoint/$Identifier/$Status/$ReturnURL' : SilverStripe\Omnipay\PaymentGatewayController
